name: monorepo-split

on:
    push:
        tags:
            - '*'

jobs:
    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                  - partner-toolkit-php
                  - partner-toolkit-wp

        steps:
            -   uses: actions/checkout@v2
            -   id: previous-tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"
            -   name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'SteinRein'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "bfiessinger"
                    user-email: "bastian.fiessinger@steinrein.com"
                    branch: "main"
                    tag: ${{ steps.previous-tag.outputs.tag }}
