name: monorepo-split

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                  - partner-toolkit-php
                  - partner-toolkit-wp

        steps:
            -   uses: actions/checkout@v2

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'SteinRein'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "bfiessinger"
                    user-email: "bastian.fiessinger@steinrein.com"
                    branch: "master"

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'SteinRein'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "bfiessinger"
                    user-email: "bastian.fiessinger@steinrein.com"
                    branch: "master"
